seed : 1
device : "cuda"

#dataset
train_data_root : 'unpaired_image_data/cat_dog/train'
train_latent_data : 'merged_latents_forwards/cat_dog_train_latents.pt'
train_embedding_data : 'merged_latents_forwards/cat-dog_train_embeddings.pt'
eval_data_root : 'unpaired_image_data/cat_dog/valid'
eval_latent_data : 'merged_latents_forwards/cat_dog_valid_latents.pt'
eval_embedding_data : 'merged_latents_forwards/cat-dog_valid_embeddings.pt'
data_length : 400
batch_size : 12
learning_rate : 2.0e-7
lr_lambda : 0.8
origin_alpha : 0 

model:
    init_g : 50.0
    divide_out : 0.1
    num_guidance_info : 1
    hidden_dim : 768
    num_layers : 2
    heads : 4
    length : 2

loss:
    negative_prompt: 'ugly, blurry, low resolution, unrealistic, distortion'
    lambda_text : 0.7
    lambda_structure : 0.1
    lambda_mean : 0.3
    lambda_negative : 1.0
    dino_threshold : 0.0
    num_condition : 1
    pnp_injection_rate : 0.8
    clip_ds_use : False
    negative_clip_use : True
    image_size : 256
    gradient : 'decrease'
    schedule_method : 'cosine'


