train :
  device : "cuda:0"
  #dataset
  data_directory : './image_data/train' #loss:data_root
  init_text : "a photography of"

  #dataloader
  batch_size : 5

  #model
  init_g : 50
  num_guidance_info : 1
  linear_in_size : 768
  num_mlp_layers : 3
  hidden_act : "gelu"

  #loss
  negative_prompt: 'ugly, blurry, low res, unrealistic, paint'
  lambda_text : 5.0
  lambda_structure : 0.5
  save_image_root : 'Train_save_images' 

  















conditions : [' on a summer day',
              ' on a spring day',
              ' on a winter day',
              ' on a autumn day',
              ' on a rainy day',
              ' on a foggy day',
              ' on a snowy day',
              ' on a sunny day',
              ' on a cloudy day',
              ' at night',
              ' at sunset',
              ' at daytime']





