seed : 1
device : "cuda"

#dataset
train_data_root : './image_data/train'
train_embedding_data : 'merged_latents_forwards/ip2p_train_embeddings.pt'
eval_data_root : './image_data/eval'
eval_embedding_data : 'merged_latents_forwards/ip2p_eval_embeddings.pt'
data_length : 2000
batch_size : 5
learning_rate : 2.0e-7
lr_lambda : 0.8
origin_alpha : 0 
Attention : False

model:
    init_g : 50.0
    divide_out : 0.1
    num_guidance_info : 1
    hidden_dim : 768
    num_layers : 8
    heads : 4
    length : 2

loss:
    negative_prompt: 'ugly, blurry, low resolution, unrealistic, paint, distortion'
    lambda_text : 0.3
    lambda_structure : 0.2
    lambda_mean : 0.7
    lambda_negative : 1.0
    n_timestep : 50
    image_guidance : 1.6
    negative_clip_use : True
    gradient : 'constant'
    schedule_method : 'cosine'


