seed : 1
device : "cuda:0"

#dataset
train_data_root : './image_data/train'
train_latent_data : 'merged_latents_forwards/train_latents.pt'
train_embedding_data : 'merged_latents_forwards/blip_train_embeddings.pt'
eval_data_root : './image_data/eval'
eval_latent_data : 'merged_latents_forwards/eval_latents.pt'
eval_embedding_data : 'merged_latents_forwards/blip_eval_embeddings.pt'
data_length : 1000
batch_size : 5
learning_rate : 0.00005
origin_alpha : 0
nu_init_text : ""
model_zero_init : False

model:
    init_g : 100.0
    divide_out : 0.2
    num_guidance_info : 1
    linear_in_size : 1536
    num_mlp_layers : 3
    hidden_act : "gelu"

loss:
    negative_prompt: 'ugly, blurry, low res, unrealistic, paint'
    lambda_text : 2.0
    lambda_structure : 1.0
    dino_threshold : 0.2
    num_condition : 1
    pnp_injection_rate : 0.9
    guidance_schedule_use : True
    dino_loss_use : True
    clip_ds_use : True
    gradient : 'increase'
    schedule_method : 'cosine'
    ##data_root = train_data_root
    ##device = device








