seed : 42
device : "cuda"

#dataset
train_data_root : './image_data/train'
train_latent_data : 'merged_latents_forwards/train_latents.pt'
train_embedding_data : 'merged_latents_forwards/zero-shot-50_train_embeddings.pt'
eval_data_root : './image_data/eval'
eval_latent_data : 'merged_latents_forwards/eval_latents.pt'
eval_embedding_data : 'merged_latents_forwards/zero-shot-50_eval_embeddings.pt'
data_length : 2000
batch_size : 5
learning_rate : 1.0e-6
lr_lambda : 0.8
epoch : 20
Attention : False

model:
    init_g : 100.0
    divide_out : 0.05
    num_guidance_info : 2
    hidden_dim : 768
    num_layers : 4
    heads : 4
    length : 2

loss:
    negative_prompt: 'ugly, low resolution, unrealistic, distortion'
    lambda_text : 0.3
    lambda_structure : 0.1
    lambda_mean : 0.7
    lambda_negative : 0.8
    dino_threshold : 0.0
    num_condition : 1
    pnp_injection_rate : 0.9
    clip_ds_use : False
    negative_clip_use : True
    image_size : 512
    gradient : 'sine'
    schedule_method : 'cosine'


