seed : 42
device : "cuda"

#dataset
train_data_root : 'unpaired_image_data/male/train'
train_latent_data : 'merged_latents_forwards/male_train_latents.pt'
train_embedding_data : 'merged_latents_forwards/male_train_embeddings.pt'
eval_data_root : 'unpaired_image_data/male/valid'
eval_latent_data : 'merged_latents_forwards/male_valid_latents.pt'
eval_embedding_data : 'merged_latents_forwards/male_valid_embeddings.pt'
data_length : 1000
batch_size : 5
learning_rate : 2.0e-7
lr_lambda : 0.9
epoch : 20
Attention : False

model:
    init_g : 100.0
    divide_out : 0.05
    num_guidance_info : 2
    hidden_dim : 768
    num_layers : 6
    heads : 4
    length : 2

loss:
    negative_prompt: 'ugly, blurry, low resolution, unrealistic, distortion'
    lambda_text : 0.3
    lambda_structure : 0.2
    lambda_mean : 0.7
    lambda_negative : 0.8
    dino_threshold : 0.0
    num_condition : 1
    pnp_injection_rate : 0.9
    negative_clip_use : True
    image_size : 512
    gradient : 'decrease'
    schedule_method : 'cosine'


