seed : 1
device : "cuda"

#dataset
train_data_root : './image_data/train'
train_latent_data : 'merged_latents_forwards/train_latents.pt'
train_embedding_data : 'merged_latents_forwards/zero-shot_train_embeddings.pt'
eval_data_root : './image_data/eval'
eval_latent_data : 'merged_latents_forwards/eval_latents.pt'
eval_embedding_data : 'merged_latents_forwards/zero-shot_eval_embeddings.pt'
data_length : 1000
batch_size : 5
learning_rate : 1.0e-6
lr_lambda : 0.5
origin_alpha : 0 

model:
    init_g : 50.0
    divide_out : 0.2
    num_guidance_info : 1
    hidden_dim : 768
    num_layers : 5
    heads : 4
    length : 2

loss:
    negative_prompt: 'ugly, blurry, low resolution, unrealistic, paint, distortion'
    clip_negative_prompt: 'ugly, blurry, low resolution, unrealistic, paint, distortion, black and white'
    lambda_text : 0.5
    lambda_structure : 0.1
    lambda_mean : 0.5
    lambda_negative : 1.0
    dino_threshold : 0.0
    num_condition : 1
    pnp_injection_rate : 0.95
    clip_ds_use : False
    negative_clip_use : True
    gradient : 'decrease'
    schedule_method : 'cosine'


